name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_bridge:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v5

    - name: Install alsa dev
      if: runner.os == 'Linux'
      run: |
          sudo apt-get update
          sudo apt-get install libasound2-dev

    - uses: Swatinem/rust-cache@v2

    - name: Build
      run: cargo build -p kissmp-bridge --verbose --release

    - name: Store Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build_results_bridge
        path: |
          ./target/release/kissmp-bridge
          ./target/release/kissmp-bridge.exe

  build_server:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest]
    steps:
    - uses: actions/checkout@v5

    - uses: Swatinem/rust-cache@v2

    - name: Build
      run: cargo build -p kissmp-server --verbose --release

    - name: Store Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build_results_server
        path: |
          ./target/release/kissmp-server
          ./target/release/kissmp-server.exe

  build_master:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
    - uses: actions/checkout@v5

    - uses: Swatinem/rust-cache@v2

    - name: Build
      run: cargo build -p kissmp-master --verbose --release

    - name: Store Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build_results_master_server
        path: |
          ./target/release/kissmp-master
